# Generated by Django 4.1.6 on 2023-02-08 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_auto_20201205_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 8, 11, 9, 34, 69151, tzinfo=datetime.timezone.utc)),
        ),
    ]
