# Generated by Django 4.1.6 on 2023-02-10 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 10, 9, 4, 12, 247254, tzinfo=datetime.timezone.utc)),
        ),
    ]
